local name = names.pollution_drill

if false then
  local drill = util.copy(data.raw["mining-drill"]["pumpjack"])
  local spawner_graphics = util.copy(data.raw["unit-spawner"]["biter-spawner"])
  local tint = {r = 1, b = 1, g = 0.5}
  util.recursive_hack_scale(spawner_graphics, 0.66)
  util.recursive_hack_make_hr(spawner_graphics)
  util.recursive_hack_tint(spawner_graphics, tint)

  util.recursive_hack_make_hr(drill)
  --util.recursive_hack_scale(drill, 3/2)
  util.recursive_hack_tint(drill, tint)

  drill.icons =
  {
    {
      icon = spawner_graphics.icon,
      icon_size = spawner_graphics.icon_size,
      tint = tint
    },
    {
      icon = drill.icon,
      icon_size = drill.icon_size,
      tint = tint
    }
  }
  drill.icon = nil
  drill.name = name
  drill.localised_name = {name}
  drill.order = "noob"
  drill.collision_box = util.area({0,0}, 1.01)
  drill.selection_box = util.area({0,0}, 1.5)
  drill.mining_speed = 0
  drill.energy_source = {type = "void"}
  drill.resource_searching_radius = 0.5
  drill.emissions_per_second = 1
  drill.collision_mask = util.buildable_on_creep_collision_mask()
  drill.resource_categories = {"basic-fluid"}
  drill.vector_to_place_result = {0, 0}
  drill.output_fluid_box = nil
  drill.base_picture = spawner_graphics.animations[4]
  drill.working_sound = spawner_graphics.working_sound
  drill.vehicle_impact_sound = spawner_graphics.vehicle_impact_sound
  drill.module_specification = nil
  drill.dying_explosion = spawner_graphics.dying_explosion
  drill.corpse = nil
  log(serpent.block(drill))
  error("Export sucessful")

end

--Generated by script!
local drill = {
  animations = {
    north = {
      layers = {
        {
          animation_speed = 0.5,
          filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead.png",
          frame_count = 40,
          height = 202,
          line_length = 8,
          priority = "high",
          scale = 0.5,
          shift = {
            -0.125,
            -0.75
          },
          tint = {
            b = 1,
            g = 0.5,
            r = 1
          },
          width = 206
        },
        {
          animation_speed = 0.5,
          draw_as_shadow = true,
          filename = "__base__/graphics/entity/pumpjack/hr-pumpjack-horsehead-shadow.png",
          frame_count = 40,
          height = 82,
          line_length = 8,
          priority = "high",
          scale = 0.5,
          shift = {
            0.5546875,
            0.453125
          },
          tint = nil,
          width = 309
        }
      }
    }
  },
  base_picture = {
    layers = {
      {
        animation_speed = 0.17999999999999998,
        direction_count = 1,
        filename = "__base__/graphics/entity/spawner/hr-spawner-idle.png",
        frame_count = 8,
        height = 354,
        line_length = 4,
        run_mode = "forward-then-backward",
        scale = 0.33000000000000003,
        shift = {
          0.061875,
          -0.04125
        },
        tint = nil,
        width = 490,
        y = 2124
      },
      {
        animation_speed = 0.17999999999999998,
        filename = "__base__/graphics/entity/spawner/hr-spawner-idle-mask.png",
        flags = {
          "mask"
        },
        frame_count = 8,
        height = 234,
        line_length = 4,
        run_mode = "forward-then-backward",
        scale = 0.33000000000000003,
        shift = {
          -0.020625,
          -0.28875000000000002
        },
        tint = nil,
        width = 276,
        y = 1404
      }
    }
  },
  base_render_layer = "lower-object-above-shadow",
  circuit_connector_sprites = {
    {
      blue_led_light_offset = {
        0.125,
        -0.59375
      },
      connector_main = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04a-base-sequence.png",
        height = 50,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.859375
        },
        tint = nil,
        width = 52,
        x = 104,
        y = 150
      },
      connector_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04b-base-shadow-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.171875,
          -0.8125
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 138
      },
      led_blue = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04e-blue-LED-on-sequence.png",
        height = 60,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 60,
        x = 120,
        y = 180
      },
      led_blue_off = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04f-blue-LED-off-sequence.png",
        height = 44,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 46,
        x = 92,
        y = 132
      },
      led_green = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04h-green-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      led_light = {
        intensity = 0.8,
        size = 0.9
      },
      led_red = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04i-red-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      red_green_led_light_offset = {
        0.109375,
        -0.703125
      },
      wire_pins = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04c-wire-sequence.png",
        height = 58,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 174
      },
      wire_pins_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04d-wire-shadow-sequence.png",
        height = 54,
        priority = "low",
        scale = 0.5,
        shift = {
          0.25,
          -0.765625
        },
        tint = nil,
        width = 70,
        x = 140,
        y = 162
      }
    },
    {
      blue_led_light_offset = {
        0.125,
        -0.59375
      },
      connector_main = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04a-base-sequence.png",
        height = 50,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.859375
        },
        tint = nil,
        width = 52,
        x = 104,
        y = 150
      },
      connector_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04b-base-shadow-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.171875,
          -0.8125
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 138
      },
      led_blue = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04e-blue-LED-on-sequence.png",
        height = 60,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 60,
        x = 120,
        y = 180
      },
      led_blue_off = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04f-blue-LED-off-sequence.png",
        height = 44,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 46,
        x = 92,
        y = 132
      },
      led_green = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04h-green-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      led_light = {
        intensity = 0.8,
        size = 0.9
      },
      led_red = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04i-red-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      red_green_led_light_offset = {
        0.109375,
        -0.703125
      },
      wire_pins = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04c-wire-sequence.png",
        height = 58,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 174
      },
      wire_pins_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04d-wire-shadow-sequence.png",
        height = 54,
        priority = "low",
        scale = 0.5,
        shift = {
          0.25,
          -0.765625
        },
        tint = nil,
        width = 70,
        x = 140,
        y = 162
      }
    },
    {
      blue_led_light_offset = {
        0.125,
        -0.59375
      },
      connector_main = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04a-base-sequence.png",
        height = 50,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.859375
        },
        tint = nil,
        width = 52,
        x = 104,
        y = 150
      },
      connector_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04b-base-shadow-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.171875,
          -0.8125
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 138
      },
      led_blue = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04e-blue-LED-on-sequence.png",
        height = 60,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 60,
        x = 120,
        y = 180
      },
      led_blue_off = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04f-blue-LED-off-sequence.png",
        height = 44,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 46,
        x = 92,
        y = 132
      },
      led_green = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04h-green-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      led_light = {
        intensity = 0.8,
        size = 0.9
      },
      led_red = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04i-red-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      red_green_led_light_offset = {
        0.109375,
        -0.703125
      },
      wire_pins = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04c-wire-sequence.png",
        height = 58,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 174
      },
      wire_pins_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04d-wire-shadow-sequence.png",
        height = 54,
        priority = "low",
        scale = 0.5,
        shift = {
          0.25,
          -0.765625
        },
        tint = nil,
        width = 70,
        x = 140,
        y = 162
      }
    },
    {
      blue_led_light_offset = {
        0.125,
        -0.59375
      },
      connector_main = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04a-base-sequence.png",
        height = 50,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.859375
        },
        tint = nil,
        width = 52,
        x = 104,
        y = 150
      },
      connector_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04b-base-shadow-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.171875,
          -0.8125
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 138
      },
      led_blue = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04e-blue-LED-on-sequence.png",
        height = 60,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 60,
        x = 120,
        y = 180
      },
      led_blue_off = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04f-blue-LED-off-sequence.png",
        height = 44,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 46,
        x = 92,
        y = 132
      },
      led_green = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04h-green-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      led_light = {
        intensity = 0.8,
        size = 0.9
      },
      led_red = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04i-red-LED-sequence.png",
        height = 46,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 48,
        x = 96,
        y = 138
      },
      red_green_led_light_offset = {
        0.109375,
        -0.703125
      },
      wire_pins = {
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04c-wire-sequence.png",
        height = 58,
        priority = "low",
        scale = 0.5,
        shift = {
          0.09375,
          -0.890625
        },
        tint = nil,
        width = 62,
        x = 124,
        y = 174
      },
      wire_pins_shadow = {
        draw_as_shadow = true,
        filename = "__base__/graphics/entity/circuit-connector/hr-ccm-universal-04d-wire-shadow-sequence.png",
        height = 54,
        priority = "low",
        scale = 0.5,
        shift = {
          0.25,
          -0.765625
        },
        tint = nil,
        width = 70,
        x = 140,
        y = 162
      }
    }
  },
  circuit_wire_connection_points = {
    {
      shadow = {
        green = {
          0.53125,
          -0.515625
        },
        red = {
          0.75,
          -0.5625
        }
      },
      wire = {
        green = {
          0.453125,
          -0.609375
        },
        red = {
          0.390625,
          -0.84375
        }
      }
    },
    {
      shadow = {
        green = {
          0.53125,
          -0.515625
        },
        red = {
          0.75,
          -0.5625
        }
      },
      wire = {
        green = {
          0.453125,
          -0.609375
        },
        red = {
          0.390625,
          -0.84375
        }
      }
    },
    {
      shadow = {
        green = {
          0.53125,
          -0.515625
        },
        red = {
          0.75,
          -0.5625
        }
      },
      wire = {
        green = {
          0.453125,
          -0.609375
        },
        red = {
          0.390625,
          -0.84375
        }
      }
    },
    {
      shadow = {
        green = {
          0.53125,
          -0.515625
        },
        red = {
          0.75,
          -0.5625
        }
      },
      wire = {
        green = {
          0.453125,
          -0.609375
        },
        red = {
          0.390625,
          -0.84375
        }
      }
    }
  },
  circuit_wire_max_distance = 9,
  collision_box = {
    {
      -1.01,
      -1.01
    },
    {
      1.01,
      1.01
    }
  },
  collision_mask = {
    "ground-tile",
    "water-tile",
    "player-layer"
  },
  drawing_box = {
    {
      -1.6000000000000001,
      -2.5
    },
    {
      1.5,
      1.6000000000000001
    }
  },
  dying_explosion = "blood-explosion-huge",
  emissions_per_second = 1,
  energy_source = {
    type = "void"
  },
  energy_usage = "90kW",
  fast_replaceable_group = "pumpjack",
  flags = {
    "placeable-neutral",
    "player-creation"
  },
  icon_size = 32,
  icons = {
    {
      icon = "__base__/graphics/icons/biter-spawner.png",
      icon_size = 32,
      tint = nil
    },
    {
      icon = "__base__/graphics/icons/pumpjack.png",
      icon_size = 32,
      tint = nil
    }
  },
  localised_name = {
    "pollution-drill"
  },
  max_health = 200,
  minable = {
    mining_time = 0.5,
    result = "pumpjack"
  },
  mining_speed = 0,
  monitor_visualization_tint = {
    b = 255,
    g = 173,
    r = 78
  },
  name = "pollution-drill",
  order = "noob",
  radius_visualisation_picture = {
    filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
    height = 12,
    tint = nil,
    width = 12
  },
  resource_categories = {
    "basic-fluid"
  },
  resource_searching_radius = 0.5,
  selection_box = {
    {
      -1.5,
      -1.5
    },
    {
      1.5,
      1.5
    }
  },
  type = "mining-drill",
  vector_to_place_result = {
    0,
    0
  },
  working_sound = {
    apparent_volume = 2,
    sound = {
      {
        filename = "__base__/sound/creatures/spawner.ogg",
        volume = 1
      }
    }
  }
}
--error(serpent.block(drill))
local subgroup =
{
  type = "item-subgroup",
  name = "pollution-drill-subgroup",
  group = "combat",
  order = "b"
}

local item =
{
  type = "item",
  name = name,
  localised_name = {name},
  localised_description = {"requires-pollution", names.required_pollution[name]},
  icons = drill.icons,
  icon = drill.icon,
  icon_size = drill.icon_size,
  flags = {},
  subgroup = subgroup.name,
  order = "aa-"..name,
  place_result = name,
  stack_size = 50
}

data:extend
{
  drill,
  item,
  subgroup
}
